bugfix: TextEditor now longer allows all formatting such as images
42BV/ui pull request #491
Opened 2020-11-17 13:26 UTC by MrHus

Quill separates the toolbar from the allowed formats. For example it is
possible to not show the "bold" toolbar item, but to allow the ctrl-b
shortcut and pasting bold text. The `format` property defines which
formatting is actually allowed.

We did not set the `formats` for the `TextEditor` which then defaults
to allow all formats. This is unexpected, developers do not expect that
for the default toolbar we provide, that the user can for example can
paste images.

The solution is adding a `formats` property to the `TextEditor` which
by default is set to all items in the default toolbar.

This way when customising the toolbar the developer can also set the
`formats` allowing only what the end user expects.

Closes #490

2020-11-19 14:30 UTC, gidomanders requested changes

2020-11-19 14:30 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +            // which formats are supported. Quill does this so
```suggestion
            // which formats are supported. Quill does this to
```

2020-11-19 14:30 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +          or using the ctrl-b shortcut it will not work.
```suggestion
          or using the ctrl-b shortcut, it will not work.
```

2020-11-19 14:30 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +          or using the ctrl-b shortcut it will not work.
In this case, bold text should work right?

2020-11-19 14:30 UTC, gidomanders commented on src/form/TextEditor/TextEditor.tsx
> +   * Optional configuration determine which formatting is allowed.
```suggestion
   * Optional configuration to determine which formatting is allowed.
```

2020-11-19 14:30 UTC, gidomanders commented on src/form/TextEditor/TextEditor.tsx
> +   * When the `'all'` string is provide all formats are allowed.
```suggestion
   * When the `'all'` string is provided, all formats are allowed.
```

2020-11-23 10:35 UTC, b-chiarini approved these changes

2020-11-23 10:43 UTC, gidomanders requested changes

2020-11-23 10:43 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +          through there is no bold button in the toolbar you can still paste
```suggestion
          though there is no bold button in the toolbar, you can still paste
```

2020-11-23 10:43 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +          bold text or using the ctrl-b shortcut.
```suggestion
          bold text or use the ctrl-b shortcut.
```

2020-11-23 10:43 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +          // When you include a format here you cannot paste or use
```suggestion
          // When you include a format here you can paste or use
```

2020-11-23 10:49 UTC, gidomanders requested changes

2020-11-23 10:49 UTC, gidomanders commented on src/form/TextEditor/TextEditor.stories.tsx
> +          throug there is no bold button in the toolbar you can still paste bold
```suggestion
          though there is no bold button in the toolbar you can still paste bold
```

2020-11-23 11:49 UTC, gidomanders approved these changes

2020-11-23 11:55 UTC, merged