feat (Typeahead, ModalPicker): Configurable page size
42BV/ui pull request #566
Opened 2021-04-13 13:46 UTC by arjanvlek

Added the ability to specify the number of suggestions for
`TypeaheadSingle` and `TypeaheadMultiple`. Also added the ability to
show all predefined options matching the input. One of our applications
needs to show as much suggestions as possible, as users need to know
which values are supported.

Added the ability to change the page size of `ModalPickerMultiple` and
`ModalPickerSingle`, for some applications it is desired to have more
than 10 items per page on screen.

2021-04-14 05:44 UTC, MrHus commented on src/form/Typeahead/single/TypeaheadSingle.tsx
> +      Array.isArray(options) && showAllSuggestionsInDropdown
The `showAllSuggestionsInDropdown` is not necessary take a look at `RadioGroup`, `Select` and `CheckboxMultipleSelect` they simply when the options is an array use the length of the array as the size.

2021-04-14 05:53 UTC, MrHus commented on src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
> +     * Optionally specify the number of elements to show per page in the modal.
I Question if we really want to be able do do this. Fetching many options will be a performance hit, and showing to many options will make the modal too large which is detrimental to the user experience. 

Can you give me an example of when this is useful in your application?

2021-04-14 09:26 UTC, arjanvlek commented on src/form/Typeahead/single/TypeaheadSingle.tsx
> +      Array.isArray(options) && showAllSuggestionsInDropdown
I have removed the `showAllSuggestionsInDropdown` prop with the latest patch.

2021-04-14 09:27 UTC, arjanvlek commented on src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
> +     * Optionally specify the number of elements to show per page in the modal.
While I agree that fetching too many options degrades performance and UX, a customer of ours has requested to increase the options slightly above 10. 

As for the typeahead, we are using predefined options, so performance is not a concern.

2021-04-16 07:54 UTC, gidomanders requested changes

2021-04-16 07:54 UTC, gidomanders commented on src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
> +      </Form>
Please also add a note about high page size deteriorating UX on smaller screens (same note as in the property comments)

2021-04-16 07:54 UTC, gidomanders commented on src/form/Typeahead/multiple/TypeaheadMultiple.stories.tsx
> +      </Form>
Here a similar note about high page size

2021-04-16 07:54 UTC, gidomanders commented on src/form/Typeahead/multiple/TypeaheadMultiple.tsx
> +     * performance issues when setting the value too high.
Please add the UX deterioration here too to make the comment exactly the same on all components. Maybe this property could even be moved to the FieldCompatibleWithPredeterminedOptions type?

2021-04-16 07:54 UTC, gidomanders commented on src/form/Typeahead/single/TypeaheadSingle.stories.tsx
> +      </Form>
Please add the aforementioned note here too

2021-04-16 07:54 UTC, gidomanders commented on src/form/Typeahead/single/TypeaheadSingle.test.tsx
> +        pageSize: undefined
You don't have to specify undefined parameters as the default is undefined

2021-04-16 07:54 UTC, gidomanders commented on src/form/Typeahead/single/TypeaheadSingle.tsx
> +     * performance issues when setting the value too high.
Same here about the deteriorating UX

2021-04-16 11:20 UTC, MrHus approved these changes

2021-04-16 11:23 UTC, gidomanders approved these changes

2021-04-16 11:23 UTC, merged